name: First Workflow

on:
 push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v6.0.1
   - name: Setup Java JDK
     uses: actions/setup-java@v5.1.0
     with:
      java-version:  17
      distribution: microsoft
   - name: Maven build
     run: mvn --batch-mode --update-snapshots verify
   - name: copy the target
     run: mkdir staging && cp target/*.jar staging
   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v6.0.0
     with:
       name: drop
       path: staging
        
       
     

    
  
  
